### ISSUE TITLE
引导层设置成透明，好像不起作用

### ISSUE THREAD

**Issue by paozhuanyinyu** [huburt-Hu/NewbieGuide#102]
NewbieGuide.with(this)
                .setLabel("Label")
                .alwaysShow(true)
                .addGuidePage(GuidePage.newInstance()
                        .setBackgroundColor(getResources().getColor(R.color.transparent))
                        .setEverywhereCancelable(true)
                        .setLayoutRes(R.layout.audio_control_activity_layout_guide_layout).show();

**Comment by cnm7625904** [comment]
要在颜色前面设置一个16进制的透明度，除了黑色以外都可以设置成透明的，#00ffffff，纯白色透明，透明度可以参考这个 https://blog.csdn.net/hewuzhao/article/details/78821954
