### ISSUE TITLE
点击高亮区域，执行完操作以后，返回当前页面，遮罩层不消失

### ISSUE THREAD

**Issue by supperyan** [huburt-Hu/NewbieGuide#103]
我的需求：
点击遮罩层高亮区域，跳转到搜索页面，搜索完毕返回后，遮罩层消失。
当前问题：
点击遮罩层高亮区域，跳转到搜索页面，搜索完毕返回后，遮罩层**不会**消失。

点击高亮区域，执行完操作以后，返回当前页面，遮罩层不消失。
请问是否有让遮罩层消失的方法？我想在高亮区域的点击事件中添加“让遮罩层消失”的方法来实现我的需求。

**Comment by supperyan** [comment]
`
    private void showNewbieGuide() {
        HighlightOptions options = new HighlightOptions.Builder()
                .setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        SearchActivity.start(getActivity());
                    }
                })
                .build();
        GuidePage page = GuidePage.newInstance().setEverywhereCancelable(true).
                addHighLightWithOptions(search, options).setLayoutRes(R.layout.view_guide_search);
        NewbieGuide.with(getActivity())
                .setLabel("guide1")
                .alwaysShow(true)
                .addGuidePage(page)
                .show();
    }`
代码如上所示。请问大佬如何实现？

**Comment by huburt-Hu** [comment]
如果你仔细看看文档，应该就不会提出这个问题了

**Comment by huburt-Hu** [comment]
controller.remove()

**Comment by shikechen** [comment]
@huburt-Hu 找到了，要先把controller引用出来，再在点击事件里调用controller.remove()
