### ISSUE TITLE
关于RecyclerView的item里用了GridView，然后使GridView的某个item高亮的问题

### ISSUE THREAD

**Issue by magic0908** [huburt-Hu/NewbieGuide#11]
我们这边需要一个页面的多个地方显示引导图高亮，我是用RecyclerView作为整个布局，里面的item使用了GridView，类似多宫格布局，但是我使用gridView.getChildAt(5)的时候返回是null，
用gridView.getAdapter().getView(length - 1,null,null)就能返回view对象。我将拿到的item.addHighLight(view)，却没有显示高亮的效果，这是怎么回事呢

这是设计图的一部分

![w 2 k3lmwhjxh_20 2 6f89](https://user-images.githubusercontent.com/23170601/33065868-b94a3fc0-cee4-11e7-9550-0f267fb6a0f8.png)

**Comment by huburt-Hu** [comment]
这样嵌套使用本身就不太好，其实一个recylerView就能实现这样的效果，现在既然这样做了，你得先确保gridview在外层recylerView中是当前可见的条目（即在屏幕中显示），然后在获取gridview的对应可见条目，获取到的view你可以通过下面的方式检测获取到view是否在屏幕上显示，如果view没有显示在屏幕上就不会高亮，说明获取到的view时错误的，或者时机不对：
```
int[] location = new int[2];
view.getLocationOnScreen(location);
Log.i("tag","x:"+location[0]+",y:"+location[1]);
```

**Comment by magic0908** [comment]
我用了Handler延时500ms，在adapter加载完成的时候可以获取到itemView了，不过我觉得这个方法还不是很好，只能先这样了。
另外楼主说到一个recylerView就可以实现这个效果，有没有类似的demo，我想知道怎么实现的

**Comment by huburt-Hu** [comment]
recylerView的Gridlayout多种布局可以实现，可以看看这个库：https://github.com/CymChad/BaseRecyclerViewAdapterHelper

可以很方便地实现

**Comment by magic0908** [comment]
这个库我一直在用，但是只用了上拉加载，添加头布局空布局等，没有用到Gridlayout负责布局的效果，有空再看看，感谢！

**Comment by zhaoziliang01** [comment]
怎么做到在adapter加载完成的时候设置高亮？

**Comment by magic0908** [comment]
@zhaoziliang01 你具体是什么需求

**Comment by zhaoziliang01** [comment]
@magic0908 gridview的数据是网络请求下来的，直接调用显示gridview中的某个item作为高亮显示 是找不到的 必须延时一下 我感觉是adapter还没加载完成 导致的

**Comment by zhaoziliang01** [comment]
@magic0908 另外我想问下 我想给高亮区域设置圆角 .addHighLight(childAt, HighLight.Type.RECTANGLE, 55)    这样设置没效果啊。。是我哪里用的不对吗

**Comment by magic0908** [comment]
@zhaoziliang01 你在 .addHighLight（childAt）的时候，childAt好像需要是view才可以，比如TextView，不能是layout，比如framelayout。你试试是不是这样

**Comment by huburt-Hu** [comment]
ViewGroup也是View，没有影响的，显示不出来的原因大都是调用显示引导层方法的时候你传入的view还没有在屏幕上显示出来，所以没有效果。调整引导层的显示时机。

**Comment by zhaoziliang01** [comment]
@magic0908 .addHighLight(view4ScoreInterflow, HighLight.Type.ROUND_RECTANGLE,30)    type改为ROUND_RECTANGLE的时候  第三个参数 才有效果。。

**Comment by zhaoziliang01** [comment]
@huburt-Hu 所以我选择了延时了0.3秒显示高亮。这样处理是可以的吧

**Comment by huburt-Hu** [comment]
如果是普通的view，可以用view.post(new Runnable(){//显示引导层}) 这样方式显示，确保view绘制完成在显示引导层，延迟0.3秒不是很稳定。如果高亮的view时在recylerView或者listview之类中，要用对应的方法判断是否显示到了屏幕上，在显示引导层，

**Comment by zhaoziliang01** [comment]
@huburt-Hu 如果高亮的view时在recylerView或者listview之类中，要用对应的方法判断是否显示到了屏幕上，在显示引导层。   这个你知道有什么方法吗
