### ISSUE TITLE
高亮的位置偏离实际位置

### ISSUE THREAD

**Issue by donlan** [huburt-Hu/NewbieGuide#13]
高亮的位置偏离实际位位置，表现为高亮的区域比需要高亮的view的位置上移一个状态栏的高度

**Comment by huburt-Hu** [comment]
如果用了转场动画，则是在动画还没有执行完成时就显示了引导层，延迟引导层的显示时机即可（在动画执行完成之后）

**Comment by donlan** [comment]
没有使用转场动画，就是oncreate后显示引导内容

**Comment by huburt-Hu** [comment]
你可以先延迟1秒再显示引导层看下是不是这个原因。
还有最好贴张图片，我不清楚到底是怎样的偏离。

**Comment by donlan** [comment]
![图片](http://upload-images.jianshu.io/upload_images/1906740-a58549838d0ba8f5.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by huburt-Hu** [comment]
是不是设置了isFullScreen(true)? 不要设置，这儿值是用于全屏（没有状态栏）显示的

**Comment by donlan** [comment]
true or false 都会出现这个问题

**Comment by huburt-Hu** [comment]
界面是从上面出现往下来的吗？手机是什么型号的？

**Comment by donlan** [comment]
就一个bar  + recyclerview   nubia nx503a  7.1.1的系统

**Comment by huburt-Hu** [comment]
可能是这个手机没法正确获取状态栏的高度，你过滤下日志，看看有没有这样一条
`I/NewbieGuide: 状态栏的高度:55`，看下：后面的高度多少？

**Comment by huburt-Hu** [comment]
这个问题是特殊机型的问题，高亮的位置是通过view.getLocationOnScreen()方法获取的，正常情况下这个方法获取的位置是包含状态栏的，你出现的这种情况可能是该方法获取的位置没有包含状态栏，针对这种情况我做了特殊处理，依赖最新版`compile 'com.github.huburt-Hu:NewbieGuide:v1.2.1'`看看还有没有这个问题。
