### ISSUE TITLE
  怎么才能够 让提示的布局 正确的显示到 被提示的View上呢？

### ISSUE THREAD

**Issue by DevXue** [huburt-Hu/NewbieGuide#14]
怎么才能够 让提示的布局 正确的显示到 被提示的View上呢？
如图：

![dds](https://user-images.githubusercontent.com/9455329/33511236-c81259be-d751-11e7-8df1-2c51663585ab.jpg)

然而不同手机屏幕尺寸也不同啊，  如果通过引入布局 修改布局的位置  这样做就不现实了吧，  有其他的办法吗？

**Comment by 897902334** [comment]
就是想办法让这个布局 跟随 高亮显示的View ，让他们的位置劲量近一些！  或者你给我们提供一个方法供我们调用  让我们自己调整位置！

**Comment by huburt-Hu** [comment]
你需要让引导层的layout中的提示语和界面的高亮view的约束保持一致，首先根布局相同，例如你这个界面最上面是banner，然后是2行的gridview，其次是高亮的view，那提示文字的view的marginTop值=banner的高度+gridview的item的高度*2 - 这个view的本身高度

**Comment by huburt-Hu** [comment]
约束相同，在不同尺寸的屏幕上就能一直显示

**Comment by 897902334** [comment]
你说的这个约束  是约束布局ConstraintLayout 吧？      还有 你说的这个 marginTop值 =banner+gridview 的高度  这些逻辑在哪里实现呢？  demo中.setLayoutRes(R.layout.view_guide)//设置引导页布局 直接把布局设置上去的    有设置setView 的方法么？  就算我设置好了宽高  那么怎么才能设置到高亮View上去呢？

**Comment by huburt-Hu** [comment]
我说的约束就是view在父布局的参数如宽高，margin值等等，不是特指ConstraintLayout。marginTop只在布局中设置啊，我说的计算都是自己算的，不是通过代码，你界面的布局中banner设置的高度是多少dp，比如说160dp，Gridview又设置了多高，比如说100dp，那引导层的layout中“实时更新小朋友..”这个view的marginTop就设置160dp+100dp-自己的高度，比如30dp，那最终marginTop就是230dp，这样“实时更新小朋友..”这个view就永远正好在高亮的view上面。

**Comment by 897902334** [comment]
@huburt-Hu   谢谢你的回答，  我试着按照你的方法试试啊！

**Comment by 897902334** [comment]
可以通过计算来实现，  但是有个问题，   如果我的最终计算结果为：330dp ，  然而在大屏幕手机上显示一点问题也没有，但是到了小屏幕手机就出现问题了，330dp直接跑到高亮View的底部了，  这种直接在xml里写死330dp不好吧，  我的想法是 提供一个setView 方法 我把布局通过inflate把布局转成View 然后动态的计算这个View就行了 ，最后把这个View设置上去即可，  或者你有啥好办法么 ？

**Comment by huburt-Hu** [comment]
dp是相对单位，如果说330dp是在320*480的手机上是在中间偏下的位置，那你的“电脑是谁发明的”这个view也在下面
