### ISSUE TITLE
A引导展示过，没有回调方法，这样就无法执行后续操作

### ISSUE THREAD

**Issue by hexiang1993** [huburt-Hu/NewbieGuide#147]
需求：版本1.0上线页面的A引导，版本2.0想要上线该页面的B引导，但是要在A引导执行之后执行。对于新用户来说，正常。但是老用户，看过A引导的，没有回调方法提供，执行后续引导

**Comment by huburt-Hu** [comment]
NewbieGuide类有一个resetLabel方法，可以重置已经显示过引导页。你可以在合适的时机调用来清除
