### ISSUE TITLE
一点点想法。

### ISSUE THREAD

**Issue by Omooo** [huburt-Hu/NewbieGuide#17]
我想既然不能智能的引导页的箭头指向高亮控件，是不是可以用PopupWindow来做这件事呢？一个全屏的半透明的PopupWindow，自定义一个布局，里面添加一个背景为白色的按钮，在引导的时候把按钮移动到需要高亮显示的控件上，**可以在瞬间移动完成后在显示按钮**。为了看的清内部逻辑，我让他三秒移动完，并且全程显示，写了个Demo，基本上能实现你写的效果，你觉得怎么样？
效果：
![](https://i.loli.net/2018/02/23/5a8f8795bcd52.gif)

**Comment by huburt-Hu** [comment]
这是一个不错的思路，由于高亮和引导布局是在两个layout中，因此需要自己通过布局参数约束让引导页的箭头指向高亮控件，不能做到智能。但是你的方案中可能会出现原始View与popwindow中高亮View位置对不上（也需要通过调整布局参数对应位置）的问题，实际上也只是把问题上面提高的问题转移到这里。还有就是每个高亮的view都需要写两遍（popwindow中），粗看下来并不能完美的解决问题。

**Comment by Omooo** [comment]
你说的写两遍View的确是个问题，不够主要是为了方便，一个方法几十行代码就写完了。
有想法在进行优化吧，比如用一个全透明的矩形框覆盖到高亮的View上面，可以避免写两遍View，但是又会带来另外一个问题：残留PopupWindow的背景色。所以只能先这样做了。
谢谢你百忙之中回复，感谢。
