### ISSUE TITLE
 java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by petersom** [huburt-Hu/NewbieGuide#172]
#110818 java.lang.IllegalArgumentException
1 com.app.hubert.guide.util.ViewUtils.getLocationInView(ViewUtils.java:47)
--
2 com.app.hubert.guide.model.HighlightView.fetchLocation(HighlightView.java:77)
3 com.app.hubert.guide.model.HighlightView.getRectF(HighlightView.java:67)
4 com.app.hubert.guide.model.RelativeGuide.getMarginInfo(RelativeGuide.java:90)
5 com.app.hubert.guide.model.RelativeGuide.getGuideLayout(RelativeGuide.java:76)
6 com.app.hubert.guide.core.GuideLayout.addCustomToLayout(GuideLayout.java:227)
7 com.app.hubert.guide.core.GuideLayout.onAttachedToWindow(GuideLayout.java:185)
8 android.view.View.dispatchAttachedToWindow(View.java:15819)
9 android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3062)
10 android.view.ViewGroup.addViewInner(ViewGroup.java:4686)
11 android.view.ViewGroup.addView(ViewGroup.java:4480)
12 android.view.ViewGroup.addView(ViewGroup.java:4452)
13 com.app.hubert.guide.core.Controller.showGuidePage(Controller.java:175)
14 com.app.hubert.guide.core.Controller.access$200(Controller.java:39)
15 com.app.hubert.guide.core.Controller$1.run(Controller.java:118)
16 android.os.Handler.handleCallback(Handler.java:836)
17 android.os.Handler.dispatchMessage(Handler.java:103)
18 android.os.Looper.loop(Looper.java:232)
19 android.app.ActivityThread.main(ActivityThread.java:6802)
20 java.lang.reflect.Method.invoke(Native Method)
21 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
22 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by petersom** [comment]
my fault!

**Comment by Wufeituzou** [comment]
@petersom 
Is there any mistake in the usage? Could you explain how to resolve it?
