### ISSUE TITLE
华为30不显示高光区

### ISSUE THREAD

**Issue by LPKgreenhand** [huburt-Hu/NewbieGuide#190]
异常bug:NewbieGuide在fragment中无法显示高光区域
异常环境：华为LND-AL30 EMUI:8.0.0 ANDROID:8.0.0
原因：不能使用矩形、椭圆高光区域，必须指定圆形或圆角矩形
流程：在activity中直接获取fragment实例的view，addHighLightWithOptions()时出现
代码：
controller = NewbieGuide.with(this)
                .setLabel("蒙板1")
                .alwaysShow(true)//总是显示
                .addGuidePage(GuidePage.newInstance()
                        .addHighLightWithOptions(ll_mine,HighLight.Shape.ROUND_RECTANGLE,options1)
                        .setLayoutRes(R.layout.zc_yd_layout)
                        .setEverywhereCancelable(false)

                )
                .addGuidePage(GuidePage.newInstance()
                        .addHighLightWithOptions(fragment_mine.getView().findViewById(R.id.ll_login_weixin),HighLight.Shape.ROUND_RECTANGLE,options2)
                        .setLayoutRes(R.layout.dl_yd_layout)
                        .setEverywhereCancelable(false)
                )
                .show();

**Comment by LPKgreenhand** [comment]
问题找到了，因为用了gt管理fragment，如有和我相同情况的老哥们要注意，显示高亮至少要在你的fragment实例化对象进入了前台一次以后再调用，不然可能获取不到这个fragment内控件的引用

**Comment by AndJason** [comment]
你好,朋友，能讲详细点嘛？ 我这边进入fragment后 都是异步获取数据后才显示引导页, 依然报空。
