### ISSUE TITLE
the highlight view is null!

### ISSUE THREAD

**Issue by xueleitt** [huburt-Hu/NewbieGuide#198]
java.lang.IllegalArgumentException
the highlight view is null!
g.b.a.a.d.e.a(HighlightView.java:12)出错堆栈

1	g.b.a.a.d.e.a(HighlightView.java:15)
2	g.b.a.a.a.l.a(GuideLayout.java:7)
3	g.b.a.a.a.l.onDraw(GuideLayout.java:4)
4	android.view.View.draw(View.java:21994)
5	android.view.View.buildDrawingCacheImpl(View.java:21257)
6	android.view.View.buildDrawingCache(View.java:21111)
7	android.view.View.draw(View.java:21713)
8	android.view.ViewGroup.drawChild(ViewGroup.java:4639)
9	android.view.ViewGroup.dispatchDraw(ViewGroup.java:4386)
10	android.view.View.updateDisplayListIfDirty(View.java:20845)
11	android.view.View.draw(View.java:21721)
12	android.view.ViewGroup.drawChild(ViewGroup.java:4639)
13	android.view.ViewGroup.dispatchDraw(ViewGroup.java:4386)
14	android.view.View.updateDisplayListIfDirty(View.java:20845)
15	android.view.View.draw(View.java:21721)
16	android.view.ViewGroup.drawChild(ViewGroup.java:4639)
17	android.view.ViewGroup.dispatchDraw(ViewGroup.java:4386)
18	android.view.View.updateDisplayListIfDirty(View.java:20845)
19	android.view.View.draw(View.java:21721)
20	android.view.ViewGroup.drawChild(ViewGroup.java:4639)

系统版本

Android 10,level 29

ROM

XiaoMi/MIUI

CPU架构

arm64-v8a

设备机型

Mi 10

bugly后台反馈报错，请问怎么解决一下

**Comment by xueleitt** [comment]
版本用的v2.4.4

**Comment by JamesMarts** [comment]
我也遇到这个问题 怎么回事啊 
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/14268052/192929971-84904f10-47e7-4755-8145-a07bdc72f89b.png">
我看到是64行报错
