### ISSUE TITLE
每次第一页高亮的view没有高亮，要第二页的控件才高亮。

### ISSUE THREAD

**Issue by zhugekongming** [huburt-Hu/NewbieGuide#21]

**Comment by huburt-Hu** [comment]
界面没有绘制完成，添加监听确保界面绘制完成再显示引导层

view.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                view.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                //show NewbieGuide
            }
        });

**Comment by zhugekongming** [comment]
问题依然存在。添加界面绘制完成监听并没有效果。

**Comment by huburt-Hu** [comment]
view是你第一页要高亮的那个view

**Comment by zhugekongming** [comment]
同样没用。

**Comment by huburt-Hu** [comment]
代码和效果截图发过来看下
