### ISSUE TITLE
MIX 2 Android 7.0 的无法展示引导的问题

### ISSUE THREAD

**Issue by zhangqinning** [huburt-Hu/NewbieGuide#22]
在Controller.java中添加 
`guideLayout.setLayerType(View.LAYER_TYPE_HARDWARE, null)`
可以解决
应该是MIUI这个版本默认给View开启硬件加速的原因
另：如果还是无法显示 尝试给guidelayout里面的View也关闭硬件加速，我是两个地方都加了的

**Comment by huburt-Hu** [comment]
有些手机是会有硬件加速的问题，实际上我的库中已经关闭了硬件加速，但是部分手机会出现无法关闭的情况，也可以在Activity层去关闭（Manifest中）。

**Comment by huburt-Hu** [comment]
好的，后面的版本我会加上这个，谢谢啦~

**Comment by zhangqinning** [comment]
我的意思是直接关闭guideLayout的硬件加速可以解决这个问题，你可以尝试下

**Comment by huburt-Hu** [comment]
事实上这个方法`guideLayout.setLayerType(View.LAYER_TYPE_HARDWARE, null)`是让view采用硬件模式。
`setLayerType(LAYER_TYPE_SOFTWARE, null);` 才是不使用硬件模式，而是采用soft模式。
下面这段话是LAYER_TYPE_HARDWARE 字段上的说明：
When hardware acceleration is turned off, hardware layers behave exactly as {@link #LAYER_TYPE_SOFTWARE software layers}.
所以你有效的结果不是因为加了这句代码。

你可以在尝试下去掉这句代码，在Manifest的显示引导层的Activity开启硬件加速，注意是开启！验证是否有效。

和你解释下原因：
因为项目用到了这个方法：
```
PorterDuffXfermode xfermode = new PorterDuffXfermode(PorterDuff.Mode.CLEAR);
        mPaint.setXfermode(xfermode);
```
所以需要关闭硬件加速，我在guideLayout中已经关闭了硬件加速，
```
//关闭当前view的硬件加速
        setLayerType(LAYER_TYPE_SOFTWARE, null);
```
这在大部分手机是有效的，但是在oppo等一些机型会出现问题，于是我尝试开启activity的硬件加速（当时怀疑这些手机默认没有开启硬件加速），你可以看到代码里有这样一段，这样做确实有效了。
```
//fix oppo等部分手机无法关闭硬件加速问题
        activity.getWindow().setFlags(WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED,
                WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED);
```
直到你现在反馈的这个问题，我就一直在想为什么同一个api在不同手机系统会有相反的效果？
在考虑到这个标识仅仅是一个int常量，因此我怀疑部分手机的系统修改弄反了这个标识位，开启和关闭硬件加速的api只是改变之前的状态，就像是取反。所以无论我怎么改，总会有部分手机显示不正确（初始状态不同）。
