### ISSUE TITLE
fragment中的显示问题

### ISSUE THREAD

**Issue by w529541319** [huburt-Hu/NewbieGuide#23]
fragment中设置alwaysShow(false)，一次都不显示，请问一下是什么原因？

**Comment by huburt-Hu** [comment]
使用2.0.1版本

**Comment by guandiku** [comment]
还是不行，为啥

**Comment by huburt-Hu** [comment]
alwaysShow(false)代表只显示一次，你到设置里面清楚下应用缓存，或者label名换一个，再次打开看看是否显示了一次

**Comment by guandiku** [comment]
可以了，改了个label，然后在fragment里传了this，之前是传getActivity()了，多谢楼主，认真负责的好人
