### ISSUE TITLE
fragment中的自定义view 没有高亮

### ISSUE THREAD

**Issue by jingyc0305** [huburt-Hu/NewbieGuide#24]
1.fragment中的自定义view 
2.通过自定义view获取控件
3.用作者的代码为这个控件设置高亮
不显示 但是点击任意消息时候 显示了一瞬间 我设置了进入/退出的动画
不知道什么原因

**Comment by huburt-Hu** [comment]
view是写在xml中还是代码添加的？或者把这个相关的代码发我看看

**Comment by jingyc0305** [comment]
是这样的 我原来是在ViewCreated中 showGuideView的 后来发现 需要高亮的View是在异步请求成功后拿到tab数据再显示的 比如Tab标签 所以估计是没有add到window中 就show了 导致不能显示 现在改成 在网络请求回调中处理完业务逻辑再show就可以了

**Comment by huburt-Hu** [comment]
嗯，基本就是顺序问题了。
