### ISSUE TITLE
你好，这个库运行在不同机型上，高亮和[setLayoutRes(R.layout.view_guide)] 位置显示错乱

### ISSUE THREAD

**Issue by yongchao1210** [huburt-Hu/NewbieGuide#3]
如题，这个库运行在不同机型上，高亮和[setLayoutRes(R.layout.view_guide)]  #，有些机型显示正常，有些机型位置显示错乱

**Comment by huburt-Hu** [comment]
请把layout的根布局设置成match_parent，layout的范围是整个手机屏幕，再去调整相应的位置

**Comment by yongchao1210** [comment]
我是这样设置的，但是有些还是会出现错乱，提示文字试图位置会有很大偏差

**Comment by huburt-Hu** [comment]
布局的xml代码给我看一下

**Comment by yongchao1210** [comment]
就是你的实例代码哇，我在七彩虹上 试了

**Comment by huburt-Hu** [comment]
这个正常的，因为这个布局是我随意添加的约束，你看imageview的约束在父布局的右侧和顶部，并且距离顶部127dp，距离右边45dp，而我高亮的view的约束是按屏幕百分比的，所以对于屏幕不同长宽比的是会有不同位置的显示

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:background="#000000">

    <ImageView
        android:src="@drawable/huiyuan_cebianlan_mengban"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginRight="45dp"
        android:layout_marginEnd="45dp"
        android:layout_alignParentTop="true"
        android:layout_alignParentRight="true"
        android:layout_alignParentEnd="true"
        android:layout_marginTop="127dp" />

</RelativeLayout>

**Comment by huburt-Hu** [comment]
其实只要高亮的view的约束与引导层layout中的view约束方式一直就不会出现这种问题

**Comment by yongchao1210** [comment]
Fragment  现在可以用不

**Comment by huburt-Hu** [comment]
fragment中可以通过getActivity()获取activity对象传入with()中
