### ISSUE TITLE
如何设置高亮区域的点击事件

### ISSUE THREAD

**Issue by tdxtxt** [huburt-Hu/NewbieGuide#30]
设置绘制矩形、圆、椭圆 区域的点击事件

**Comment by huburt-Hu** [comment]
展示引导的时候关注点应该是引导显示得内容吧，高亮的区域可以让引导消失后再让用户去点击。

如果你实在要引导中点击，可以在自定义的layout中相对应的位置添加一个透明的View给这个view设置点击事件。

**Comment by shikechen** [comment]
@huburt-Hu 你好！请问最新的库，如何点击高亮区域让蒙层消失？没找到调用蒙层消失的方法。。
