### ISSUE TITLE
你好，有多个引导页，如果我想从第二页出发引导页某控件进入第一页引导页，有方法提供吗(Hello, there are more than one guide page, if I want to start from the second  page to the first page, is there a method to provide?)

### ISSUE THREAD

**Issue by soyoungboy** [huburt-Hu/NewbieGuide#35]
你好，有多个引导页，如果我想从第二页出发引导页某控件进入第一页引导页，有方法提供吗(Hello, there are more than one guide page, if I want to start from the second  page to the first page, is there a method to provide?)

**Comment by huburt-Hu** [comment]
v2.2.1版本新增方法用于控制引导页的回退，满足你的需求，具体可以看readme
