### ISSUE TITLE
底层布局滑动事件没被拦截

### ISSUE THREAD

**Issue by LomoLin** [huburt-Hu/NewbieGuide#37]
出现引导层后，底层布局里的scrollview依然可以滑动

**Comment by huburt-Hu** [comment]
之前是没有拦截事件的设置，我修改一下，下午回会更新一个版本，添加这个配置。

**Comment by huburt-Hu** [comment]
引导层默认会抢夺焦点，无法滑动

**Comment by LomoLin** [comment]
现在的问题就是底层布局可以滑动

**Comment by huburt-Hu** [comment]
使用的是哪个版本？除非你上层拦截事件，不然肯定是引导层获得事件
