### ISSUE TITLE
Demo中使用Shape类型为"CIRCLE",设置padding值是无效的。

### ISSUE THREAD

**Issue by zhoupeng2** [huburt-Hu/NewbieGuide#40]
NewbieGuide.with(FirstActivity.this)
                        .setLabel("anchor")
                        .anchor(anchorView)
                        .alwaysShow(true)//总是显示，调试时可以打开
                        .addGuidePage(GuidePage.newInstance()
                                .addHighLight(btnAnchor, HighLight.Shape.CIRCLE, 1195)
                                .setLayoutRes(R.layout.view_guide_anchor))
                        .show();
你好，请看看

**Comment by huburt-Hu** [comment]
这个是round，表示圆角，只有圆角矩形有效，后面应该还有一个padding参数

**Comment by zhoupeng2** [comment]
@huburt-Hu  .addHighLight(llayout_novice_welfare, HighLight.Shape.CIRCLE,5,11150)  padding 还想没用。。有空请帮忙看看，感谢！

**Comment by huburt-Hu** [comment]
之前是我遗漏了CIrcle的padding，现在修复了，我更新一个版本

**Comment by zhoupeng2** [comment]
good job！
