### ISSUE TITLE
recyclerview中高亮具体的Item有问题

### ISSUE THREAD

**Issue by jeffreyxuworld** [huburt-Hu/NewbieGuide#41]
通过
View view = layoutManager.findViewByPosition(3);
或者
View view = mRecyclerView.getChildAt(3);
得到的view放到addHighLight里，
不能使具体的itemview高亮，直接APP无响应了卡死了。

**Comment by huburt-Hu** [comment]
得先判断这个view是否在界面上显示，显示得情况下才显示引导层
