### ISSUE TITLE
高量控件黑屏

### ISSUE THREAD

**Issue by Michelle0716** [huburt-Hu/NewbieGuide#42]
高量虚线正常，被圈控件以黑色填充显示
![Uploading image.png…]()

**Comment by huburt-Hu** [comment]
1.确认手机设置是否开启了强制硬件加速；
2.如果没有，在Manifest中显示引导层的Activity开启硬件加速：android:hardwareAccelerated="true"
这两步之后还没有解决的话，告诉我手机平台以及系统版本

**Comment by zengx1998** [comment]
大佬 荣耀x30i 进入引导界面黑屏
