### ISSUE TITLE
产品需要实现强引导，高亮的view区域是否可以直接继承自己之前的点击事件，并且暴露一个可以自定义的点击事件出来？

### ISSUE THREAD

**Issue by dukunpeng** [huburt-Hu/NewbieGuide#43]
感谢分享！1.x升级2.x思路更清晰了，期待更新

**Comment by dukunpeng** [comment]
希望作者能 将对高亮部分进行解释的带箭头文案区域 单独抽出来，添加的时候带参数 （LEFT,TOP,RIGHT,BOTTOM...）表示在指定目标高亮view的相对位置，目前我有这个需求，暂时做法是通过获取高亮view在屏幕中的位置，然后在setOnLayoutInflatedListener里面将我要提示的文案设置到刚才获取的位置附近

**Comment by huburt-Hu** [comment]
你指的是高亮view的点击事件嘛？这个可以考虑添加；
但是第二条回复的话应该不会考虑，当初就是觉得相对位置用代码调试比较麻烦，所以才使用xml的方式，目前这种方式能满足任何自定义情况，只是采用相对位置比那种api的繁琐的一点，但通用性更强。

**Comment by dukunpeng** [comment]
感谢回复！赞
