### ISSUE TITLE
addHighLight（view）,如果view在ScrollView中，view位置发生变化,浮层还在原先的位置

### ISSUE THREAD

**Issue by lnj721** [huburt-Hu/NewbieGuide#44]

**Comment by LomoLin** [comment]
我看源码是使用getHitRect来获取高亮位置，可是当ScrollView滑动，测试getHitRect获取的Rect对象值是不变的

**Comment by LomoLin** [comment]
我将获取高亮区域的代码改成以下代码，请问下这样做是否合适
`public static Rect getLocationInView(View child) {
        if (child == null) {
            throw new IllegalArgumentException("child can not be null .");
        }

        Rect result = new Rect();
        int[] location = new int[2];
        child.getLocationOnScreen(location);
        result.left = location[0];
        result.top = location[1];
        result.right = result.left + child.getMeasuredWidth();
        result.bottom = result.top + child.getMeasuredHeight();

        return result;
    }`

**Comment by huburt-Hu** [comment]
这是我第一版的做法，这样做设置anchor就会有问题，并且也不能解决你的问题。引导层的高亮只有在初始化的时候才会获取位置，也只有一次，你的scrollView滚动后，肯定要再次刷新引导层。引导层并没有监听视图变化，所以通知刷新得你自己完成。

**Comment by LomoLin** [comment]
十分感谢抽空解答我的疑问哈

**Comment by snowjade** [comment]
就算再次刷新引导层，浮层位置还是原先的位置 不会变。 @huburt-Hu
