### ISSUE TITLE
浮层背景支持设置图片吗  

### ISSUE THREAD

**Issue by wenshuo001** [huburt-Hu/NewbieGuide#45]

**Comment by huburt-Hu** [comment]
整体背景目前只支持颜色，局部的话可以通过在xml中自定义设置。
一般也不会用图片来凸显高亮的吧？不知道有没有设计图看下要实现何种效果。

**Comment by ChongZiWenZi** [comment]
https://pan.baidu.com/s/1kmF32jwFGizQA-TKqadHrA     设计图是这样子的   不知您的库可以支持做成这种效果吗

**Comment by huburt-Hu** [comment]
这个背景不是图片吧，就是一个蓝色半透明。其实这种效果，可以在自定义的xml中实现，也就是说手指指向的高亮并不是用镂空的方式展示，而在在xml中在写一套布局，引导层显示得时候看到的是在xml中声明的那个高亮view

**Comment by ChongZiWenZi** [comment]
嗯 谢谢回答   我还想问下怎么取消浮层的点击事件销毁  要只有点击高亮控件才能销毁浮层

**Comment by huburt-Hu** [comment]
.setEverywhereCancelable(false)//是否点击任意位置消失引导页
你可以在xml中高亮相同位置设置一个透明的view，然后在.setLayoutRes(R.layout.view_guide_dialog, R.id.btn_ok)第二参数中传入这个view的id，这样只有点击这个view才能消失引导层

**Comment by huburt-Hu** [comment]
和上面结合的话，就不用再写透明的view了，直接给引导层对应的高亮view设置点击消失

**Comment by ChongZiWenZi** [comment]
嗯嗯  好的 谢谢
