### ISSUE TITLE
高亮地方的颜色能不能自己设置？

### ISSUE THREAD

**Issue by dukunpeng** [huburt-Hu/NewbieGuide#46]

**Comment by huburt-Hu** [comment]
设置是没有，不过有一种套路：在自定义xml中高亮的位置在写一个与高亮view相同的布局，然后设置颜色，也就是说显示引导层之后看到的不再是下方的那个view，而是另一个在引导层的view

**Comment by dukunpeng** [comment]
其实我是想要透明的颜色，因为每个页面的颜色可能有不一样的

**Comment by huburt-Hu** [comment]
readme 和 demo 里都有啊
