### ISSUE TITLE
setLayoutRes 中可以设置点击后 dismiss 的 id，但是使用 RelativeGuide 就不行了

### ISSUE THREAD

**Issue by DanteAndroid** [huburt-Hu/NewbieGuide#54]
RelativeGuide 的构造中传入 GuideView 的布局，但是没法设置点击后消失 GuideView 的按钮 id。
而 setLayoutRes 既可以传布局，也可以设置按钮 id。
如果两个同时使用，会出现两个 GuideView

**Comment by huburt-Hu** [comment]
麻烦仔细看看README

**Comment by DanteAndroid** [comment]
看了几遍，没有找到相关方法。

**Comment by ydz00ydz** [comment]
请问找到方法了么
