### ISSUE TITLE
HighLight.Shape.ROUND_RECTANGLE 没有效果

### ISSUE THREAD

**Issue by DanteAndroid** [huburt-Hu/NewbieGuide#55]
高亮按钮的边框 设置为 HighLight.Shape.ROUND_RECTANGLE 没有效果。效果与 HighLight.Shape.RECTANGLE 一致，都是标准的长方形。 CIRCLE 正常，为圆形

**Comment by huburt-Hu** [comment]
麻烦仔细看看README

**Comment by DanteAndroid** [comment]
又看了一遍。我猜测是需要传一个 int 值？如果是这样的话，我建议默认设置为 HighLight.Shape.ROUND_RECTANGLE 时，给一个默认的圆角，而不是必须要传 int
