### ISSUE TITLE
ScrollView用代码滑动后高亮位置没有跟着改变

### ISSUE THREAD

**Issue by chensuyu** [huburt-Hu/NewbieGuide#56]
您好，我在一个页面需要多步引导，我在第一步引导完成后需要将页面滑动到ScrollView的最低端显示引导，目前的做法是在第一页的onRemoved（）方法中调用Scrollview.fullScroll(ScrollView.FOCUS_DOWN)方法，然后监听滑动到底部的时候显示第二层引导页，但是现在高亮位置没有跟着变，还处在原来的位置，请问我需要做什么刷新操作吗？如果有具体怎么写能否告知一下，非常谢谢！

**Comment by huburt-Hu** [comment]
可以参照demo里recylerview的做法

**Comment by chensuyu** [comment]
您好，感谢您的回答，但是我是在Scrollview里面使用的，除了layoutManager.findViewByPosition(targetPosition)不一样外，剩余的代码都一致，我现在解决了这个问题了，采用的是指定RectF高亮这种方法

**Comment by Nstd** [comment]
> 您好，感谢您的回答，但是我是在Scrollview里面使用的，除了layoutManager.findViewByPosition(targetPosition)不一样外，剩余的代码都一致，我现在解决了这个问题了，采用的是指定RectF高亮这种方法

在华为上适配还是有问题
