### ISSUE TITLE
魅族商店的 crash

### ISSUE THREAD

**Issue by DanteAndroid** [huburt-Hu/NewbieGuide#59]
[testout_log.txt](https://github.com/huburt-Hu/NewbieGuide/files/2264579/testout_log.txt)
Hi，我们App上架魅族商店时不通过，上面是报错日志（其他商店都OK），是在库里发生的空指针，我在`controller.show()`的时候直接 try catch 还是一样的报错，麻烦帮忙看看~

**Comment by huburt-Hu** [comment]
是不是使用了showPage方法？能把调用的地方给我看下嘛

**Comment by DanteAndroid** [comment]
![image](https://user-images.githubusercontent.com/10005563/43876686-bf2e4a1a-9bc8-11e8-9f8d-45d1ae13a29c.png)
@huburt-Hu

**Comment by huburt-Hu** [comment]
我更新了一个版本修复你这个问题啊，你试试4.4.2

**Comment by huburt-Hu** [comment]
我更新了一个版本修复你这个问题啊，你试试4.4.2
