### ISSUE TITLE
指向GridView中的某个item高亮无效？

### ISSUE THREAD

**Issue by xiaoX3** [huburt-Hu/NewbieGuide#6]
楼主，我需要在指向一个GridView中的一个item高亮。
通过adapter的getview方法找到convertView然后addHighlight的。貌似没效果？
用convertView.findViewById找到子View也不行。

` mWxStoreView = mCateNameGridViewAdapter.getView(0, null, null);
                      ImageView icon = (ImageView)
 mWxStoreView.findViewById(R.id.id_home_cate_name_gridview_img);
NewbieGuide.with(getActivity())//传入fragment .setLabel("guide2")//设置引导层标示，必传！否则报错
 .addHighLight(mWxStoreView , HighLight.Type.RECTANGLE)//添加需要高亮的view

 .addHighLight(loopViewPager, HighLight.Type.RECTANGLE)//添加需要高亮的view
                                .setLayoutRes(R.layout.view_guide)//自定义的提示layout，不要添加背景色，引导层背景色通过setBackgroundColor()设置
                                .alwaysShow(true)
                                .show();//直接显示引导层`

**Comment by huburt-Hu** [comment]
使用的方法不正确，通过  View childAt = gridView.getChildAt(0); 才能获取到正确的view
gridView.post(new Runnable() {
            @Override
            public void run() {
                View childAt = gridView.getChildAt(0);
                NewbieGuide.with(GridViewActivity.this)
                        .setLabel("grid_view_guide")
                        .addHighLight(childAt, HighLight.Type.RECTANGLE)
                        .setLayoutRes(R.layout.view_guide)
                        .alwaysShow(true)
                        .show();
            }
        });
之所以放在post中是因为gridview没有加载完成时子view的宽高属性都为0

**Comment by xiaoX3** [comment]
感谢楼主！you save my all day！

**Comment by huburt-Hu** [comment]
以上方法是针对一加载就会出现的子view，如果你要高亮的view是需要gridview滑动后才会出现的话，需要通过setOnScrollListener()监听判断你要高亮的子view是否显示在界面上，才能调用显示引导层的方法。因为高亮view需要获取该view在屏幕上的位置，如果该view都没有显示在界面上，当然无法高亮

**Comment by xiaoX3** [comment]
好的，明白了。
