### ISSUE TITLE
麻煩看一下

### ISSUE THREAD

**Issue by DanteAndroid** [huburt-Hu/NewbieGuide#62]
https://github.com/huburt-Hu/NewbieGuide/issues/59
这个 issue 不知道您为什么早早地关了，是因为我没及时回吗？
因为要上架到市场，所以拜托帮帮忙哈

**Comment by huburt-Hu** [comment]
解决的话回复一下

**Comment by DanteAndroid** [comment]
谢谢，应该是解决了。
