### ISSUE TITLE
版本从2.1升级到2.4后，原来的高亮位置全部偏移到下方了

### ISSUE THREAD

**Issue by cheegon** [huburt-Hu/NewbieGuide#64]
版本从2.1升级到2.4后，原来的高亮位置全部偏移到下方了

**Comment by huburt-Hu** [comment]
应该是修改“默认anchor由decorView更改为android.R.id.content”这个引起的，你可以把anchor设置为DecorView试试

**Comment by cheegon** [comment]
问题解决了,确实需要设定anchor为decorView,谢谢
