### ISSUE TITLE
LinearLayout 使用layout_weight的时候，高亮布局不能设置基于屏幕水平居中

### ISSUE THREAD

**Issue by TopTime1** [huburt-Hu/NewbieGuide#66]
![image](https://user-images.githubusercontent.com/7701170/44437391-b3128380-a5ec-11e8-8a8c-8e5bf07d3332.png)
![image](https://user-images.githubusercontent.com/7701170/44437397-b9086480-a5ec-11e8-9ee5-aea9619aecc4.png)
![image](https://user-images.githubusercontent.com/7701170/44437400-bdcd1880-a5ec-11e8-9a09-57fb5dd00041.png)
![image](https://user-images.githubusercontent.com/7701170/44437411-c6255380-a5ec-11e8-8a76-afe65e7a04a0.png)

**Comment by huburt-Hu** [comment]
遇到问题先仔细读一下文档，还不能解决就看代码，不要一上来就问，这样永远没有什么成长。
