### ISSUE TITLE
怎么主动关闭蒙层？

### ISSUE THREAD

**Issue by leibown** [huburt-Hu/NewbieGuide#67]
怎么主动关闭蒙层？

**Comment by gaohequan** [comment]
@leibown  这个功能你实现了么？

**Comment by leibown** [comment]
> @leibown 这个功能你实现了么？

 NewbieGuide.with(activity).remove()方法可以关闭蒙层

**Comment by gaohequan** [comment]
> > @leibown 这个功能你实现了么？
> 
> NewbieGuide.with(activity).remove()方法可以关闭蒙层
没有您说的这个方法。我使用的是NewbieGuide.with(this).build().remove()；这个方法 但是无法关闭。2.4.0版本

**Comment by leibown** [comment]
> > > @leibown 这个功能你实现了么？
> > 
> > 
> > NewbieGuide.with(activity).remove()方法可以关闭蒙层
> > 没有您说的这个方法。我使用的是NewbieGuide.with(this).build().remove()；这个方法 但是无法关闭。2.4.0版本

我是这样弄的，版本也是2.4你可以参考下
https://ws3.sinaimg.cn/large/006tNbRwgy1fvfsnl4odyj31kw0qm7cq.jpg

**Comment by gaohequan** [comment]
@leibown   感谢 我参考了 一下 发现builder.build()与build.show() 是两个对象。 已解决。
