### ISSUE TITLE
依赖添加之后，产生错误

### ISSUE THREAD

**Issue by 906798724** [huburt-Hu/NewbieGuide#7]
楼主你好，我在引入这个依赖包之后，
产生了以下错误
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by huburt-Hu** [comment]
检查一下compileSdkVersion的版本是否低于25

**Comment by 906798724** [comment]
这个对sdk有要求的？我的是23的 周磊 在2017年10月29日 12:52，hu 写道： 检查一下compileSdkVersion的版本是否低于25 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by huburt-Hu** [comment]
因为我的库中用到support-v4的Fragment，而support的包版本需要与compileSdkVersion的版本相一致，我用的25，如果你用23就会提示找不到某些关联的内容，有两个解决方案，一个是你把你的compileSdkVersion也改成25，还有如果你项目里也依赖的support-v4的话，可以这样引用我的库：
compile ('com.github.huburt-Hu:NewbieGuide:v1.1.0'){
        exclude group: 'com.android.support'//剔除我库总support的依赖
    }
ps：相同的库依赖，as会默认使用高版本的

**Comment by 906798724** [comment]
好的，我试试，谢谢 周磊 在2017年10月29日 13:17，hu 写道： 因为我的库中用到support-v4的Fragment，而support的包版本需要与compileSdkVersion的版本相一致，我用的25，如果你用23就会提示找不到某些关联的内容，有两个解决方案，一个是你把你的compileSdkVersion也改成25，还有如果你项目里也依赖的support-v4的话，可以这样引用我的库： compile ('com.github.huburt-Hu:NewbieGuide:v1.1.0'){ exclude group: 'com.android.support'//剔除我库总support的依赖 } ps：相同的库依赖，as会默认使用高版本的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
