### ISSUE TITLE
是否支持中途退出引导的功能

### ISSUE THREAD

**Issue by fanlb** [huburt-Hu/NewbieGuide#71]
假设在新版本中设置了5个引导页面, 每个引导页面添加一个"跳过"按钮, 期望用户点击跳过按钮后引导层消失 ,想问该接口是否有实现呢 ?

**Comment by mingxin-yang** [comment]
引导层消失使用controller.remove()方法就可以了，跳过按钮的监听阅读readme，里面有方法
