### ISSUE TITLE
添加全屏View

### ISSUE THREAD

**Issue by ChenJia-X** [huburt-Hu/NewbieGuide#78]
现在有个需求是不需要高亮（因为各种原因导致不一定能出现高亮的控件），直接添加一个全屏的图片作为引导。看了好几遍找不到这个功能。

我目前的实现方式是，给HighlightOptions设置点击事件A，在其中用WindowManager添加全屏view，并给全屏View设置点击事件B，手动结束引导。
但是目前有个**问题**，点击非高亮区域无法触发点击事件A，只能setEverywhereCancelable(false)，强制用户点击高亮区域。
**能不能开放非高亮区域的点击事件？或者直接添加View作为引导页？**

**Comment by huburt-Hu** [comment]
完全可以做到啊，不设置高亮，只设置一个layoutRes就可以了
