### ISSUE TITLE
NewbieGuide在fragment中添加ChangedListener监听，onRemoved()会执行2次

### ISSUE THREAD

**Issue by uty3714** [huburt-Hu/NewbieGuide#80]
(kotlin)NewbieGuide在fragment中添加setOnGuideChangedListener监听，onRemoved()会执行2次，但是换fragment的宿主activity 是正常的。
compile 'com.github.huburt-Hu:NewbieGuide:v2.4.0'

**Comment by huburt-Hu** [comment]
v2.4.2已修复这个问题

**Comment by uty3714** [comment]
谢谢
