### ISSUE TITLE
怎么样监听点击特定区域关闭？

### ISSUE THREAD

**Issue by palorotolo** [huburt-Hu/NewbieGuide#83]
![853890522335504938.jpg](https://i.loli.net/2018/10/15/5bc3f39e0997b.jpg)

比如点击【我知道啦】就关闭，这是目前的代码：
````
View itemView = recyclerView.getChildAt(8);
HighlightOptions options = new HighlightOptions.Builder()
        .setRelativeGuide(new RelativeGuide(R.layout.view_guide_simple,
                Gravity.TOP, 50) {
            @Override
            protected void onLayoutInflated(View view) {
//                                TextView textView = view.findViewById(R.id.tv);
//                                textView.setText("inflated");
            }
        })
        .setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Toast.makeText(
                        RecyclerViewActivity.this,
                        "highlight click",
                        Toast.LENGTH_SHORT).show();
            }
        })
        .build();
GuidePage guidePage = GuidePage.newInstance()
        .addHighLightWithOptions(itemView, options);
NewbieGuide.with(RecyclerViewActivity.this)
        .setLabel("guide1")
        .alwaysShow(true)
        .addGuidePage(guidePage)
        .show();

**Comment by GoldDreams** [comment]
.setLayoutRes(R.layout.guide_got_it_layout)   //你的需要点击的布局
                        .setOnLayoutInflatedListener(new OnLayoutInflatedListener() {
                            @Override
                            public void onLayoutInflated(View view, final Controller controller) {
//找到你需要点击的按钮添加监听
                                view.findViewById(R.id.txt_ok).setOnClickListener(new View.OnClickListener() {
                                    @Override
                                    public void onClick(View v) {
                                        controller.remove();
                                    }
                                });
                            }
                        })
