### ISSUE TITLE
使用沉浸式，高亮地方会下降

### ISSUE THREAD

**Issue by FynnJason** [huburt-Hu/NewbieGuide#86]
使用沉浸式.fitsSystemWindows(true)，会让高亮下降一个状态栏的高度，请问怎么动态可以调整高度？

**Comment by huburt-Hu** [comment]
setAnchor设置你页面的根布局

**Comment by FynnJason** [comment]
何时调用setAnchor，没有在链式调用中找到该方法

**Comment by FynnJason** [comment]
已通过文档中改好，谢谢
