### ISSUE TITLE
建议:可以队列式方式显示多个引导页

### ISSUE THREAD

**Issue by lowly360** [huburt-Hu/NewbieGuide#9]
感谢楼主这个库,用了之后用引导页,的确省事好多.
但是使用过程中,当想实现一个一个显示不同引导页的时候,用现有库开放的Api,接口实现起来代码比较重复.(OnGuideChangedListener.onRemoved 的时候显示下一个Controller)
建议下一版本可以考虑添加管理多个Controller的控制类

**Comment by huburt-Hu** [comment]
感谢你的建议，我会设计一下api来支持便捷地连续多页显示引导页
